//! View dispatch: from a runtime kind to a monomorphic kernel.

use gt_core::adj::{AdjList, Incident, Lookup, NoLookup};
use gt_core::error::PropError;
use gt_core::graph::{EdgeList, Endpoints, GraphRef, VertexList};
use gt_core::ids::VertexId;
use gt_core::view::{Filtered, MaskFilter, Reverse, Undirect};

/// The six graph views, exhaustively.
///
/// `graph_filtering.hh:102-130` derives these from the `hana::cartesian_product`
/// of three booleans, filtered and de-duplicated. The fourth combination --
/// undirected *and* reversed -- is dropped by a value-level computation that a
/// caller writing `graph_view_t<false, true, f>` directly can bypass. Here
/// `Rev<Und<_>>` is an ill-formed type and there is no arm to write.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum ViewKind {
    /// `&AdjList`.
    Directed,
    /// `Und<&AdjList>`.
    Undirected,
    /// `Rev<&AdjList>`.
    Reversed,
    /// `Filtered<&AdjList, MaskFilter>`.
    DirectedFiltered,
    /// `Filtered<Und<&AdjList>, MaskFilter>`.
    UndirectedFiltered,
    /// `Filtered<Rev<&AdjList>, MaskFilter>`.
    ReversedFiltered,
}

impl ViewKind {
    /// Every view, in the order `get_graph_views` emits them
    /// (`graph_filtering.hh:101-128`): the three unfiltered kinds, then the
    /// filtered mirror of each.
    pub const ALL: [ViewKind; 6] = [
        ViewKind::Directed,
        ViewKind::Undirected,
        ViewKind::Reversed,
        ViewKind::DirectedFiltered,
        ViewKind::UndirectedFiltered,
        ViewKind::ReversedFiltered,
    ];

    /// The views a [`BidiGraphKernel`] can run on.
    ///
    /// This is `always_directed` (`graph_filtering.hh:135-138`): the
    /// cartesian product `{directed} x {reversed, not} x {filtered, not}`,
    /// which after `hana::to<set_tag>` is **four** distinct types, not three.
    /// `Rev<&AdjList>` and `Filtered<Rev<&AdjList>, _>` are directed graphs
    /// whose `in_edges` is the base's `out_edges`
    /// (`graph_adaptor.hh` `reverse_graph`, mirrored by
    /// `Bidirectional for Rev<G>`), so excluding them would refuse a view the
    /// C++ instantiates.
    pub const DIRECTED: [ViewKind; 4] = [
        ViewKind::Directed,
        ViewKind::Reversed,
        ViewKind::DirectedFiltered,
        ViewKind::ReversedFiltered,
    ];

    /// Position in [`ALL`](Self::ALL).
    ///
    /// An exhaustive match with no catch-all, so the const block below turns
    /// any drift between the variant list and [`ALL`](Self::ALL) into
    /// `error[E0080]` and a seventh variant into `error[E0004]` here as well
    /// as in [`AnyGraph::dispatch`]. Defect #47's shape: one list, checked.
    pub const fn rank(self) -> usize {
        match self {
            ViewKind::Directed => 0,
            ViewKind::Undirected => 1,
            ViewKind::Reversed => 2,
            ViewKind::DirectedFiltered => 3,
            ViewKind::UndirectedFiltered => 4,
            ViewKind::ReversedFiltered => 5,
        }
    }

    /// Whether this view has predecessors, i.e. whether
    /// [`dispatch_bidi`](AnyGraph::dispatch_bidi) has an arm for it.
    ///
    /// `in_edges(v, undirected_adaptor)` returns an empty range rather than
    /// failing (`graph_adaptor.hh:219-227`, defect #12); the two undirected
    /// kinds answer `false` here instead, and the dispatcher refuses them.
    pub const fn is_directed(self) -> bool {
        match self {
            ViewKind::Directed
            | ViewKind::Reversed
            | ViewKind::DirectedFiltered
            | ViewKind::ReversedFiltered => true,
            ViewKind::Undirected | ViewKind::UndirectedFiltered => false,
        }
    }
}

// The two inventories above are generated by hand and checked by the
// compiler: `ALL` against `rank`'s exhaustive match (injective and total, so
// exactly the six), and `DIRECTED` against `is_directed` (complete, in `ALL`
// order, no duplicates). A wrong edit is `error[E0080]`, never a silently
// short accepted-set in a `ViewError`.
const _: () = {
    let mut i = 0;
    while i < ViewKind::ALL.len() {
        assert!(
            ViewKind::ALL[i].rank() == i,
            "ViewKind::ALL disagrees with ViewKind::rank"
        );
        i += 1;
    }

    let mut directed = 0;
    let mut i = 0;
    while i < ViewKind::ALL.len() {
        if ViewKind::ALL[i].is_directed() {
            directed += 1;
        }
        i += 1;
    }
    assert!(
        directed == ViewKind::DIRECTED.len(),
        "ViewKind::DIRECTED does not list every directed view"
    );

    let mut i = 0;
    while i < ViewKind::DIRECTED.len() {
        assert!(
            ViewKind::DIRECTED[i].is_directed(),
            "ViewKind::DIRECTED lists an undirected view"
        );
        if i > 0 {
            assert!(
                ViewKind::DIRECTED[i - 1].rank() < ViewKind::DIRECTED[i].rank(),
                "ViewKind::DIRECTED is out of order or repeats a view"
            );
        }
        i += 1;
    }
};

/// Why a dispatched call did not reach a kernel.
///
/// Two conditions, kept apart. graph-tool has one: `DispatchNotFound`, whose
/// message is "This is a graph_tool bug. :-(" (`dispatch.hh:86-88`), so a
/// caller who passed an undirected graph to a predecessor-using algorithm and
/// a genuine codegen hole read the same sentence.
///
/// [`DispatchError`](gt_core::error::DispatchError) is not reused here: its
/// `offered`/`accepted` are [`ValueKind`](gt_core::prop::ValueKind)s, and
/// filling those in with a fabricated member to describe a *view* mismatch is
/// precisely the failure DESIGN.md section 6 records for a transposed
/// `value_subset!` row -- "a runtime `DispatchError` naming the **wrong** type
/// as offered and listing it as accepted, strictly worse than
/// `DispatchNotFound`, which at least prints honestly".
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum ViewError {
    /// A filter mask was shorter than the index bound it was offered for.
    ///
    /// Raised by [`Filtered::masked`], against the *unfiltered* bounds
    /// (`graph_filtering.cc:42-46`), and only reachable from the three
    /// filtered arms.
    Mask(PropError),
    /// A [`BidiGraphKernel`] was offered a view with no predecessors.
    NotDirected {
        /// The view the caller asked for.
        offered: ViewKind,
        /// The views this call site accepts, always
        /// [`ViewKind::DIRECTED`].
        accepted: &'static [ViewKind],
    },
}

impl std::fmt::Display for ViewError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            ViewError::Mask(e) => write!(f, "filter: {e}"),
            ViewError::NotDirected { offered, accepted } => write!(
                f,
                "view: {offered:?} has no in-edges; this kernel accepts {accepted:?}"
            ),
        }
    }
}

impl std::error::Error for ViewError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> {
        match self {
            ViewError::Mask(e) => Some(e),
            ViewError::NotDirected { .. } => None,
        }
    }
}

impl From<PropError> for ViewError {
    #[inline]
    fn from(e: PropError) -> ViewError {
        ViewError::Mask(e)
    }
}

/// A kernel monomorphised over every view.
///
/// Object-unsafe by construction, therefore always monomorphised -- the same
/// property as `run_action`'s `auto&&` generic lambda
/// (`graph_filtering.hh:189-200`). The bound set is the *read* surface a
/// generic algorithm needs; note it includes [`VertexList`], [`EdgeList`] and
/// [`Endpoints`], not just incidence, because `vertices(g)`, `edges(g)` and
/// `edge(u, v, g)` are among the most-used BGL accessors and a view that
/// implements only incidence cannot back a generic algorithm.
pub trait GraphKernel {
    /// What the kernel produces.
    type Out;
    /// Run at one concrete view.
    fn call<G>(self, g: G) -> Self::Out
    where
        G: GraphRef + VertexList + EdgeList + Endpoints;
}

/// The same, for kernels that need predecessors.
///
/// `ALWAYS_DIRECTED` is worth declaring only if something can consume it.
/// With a single [`GraphKernel`], no dispatched action can call `in_edges` at
/// all, because the type parameter is not bounded on
/// [`Bidirectional`](gt_core::graph::Bidirectional) and bounding it would
/// break the undirected arms.
pub trait BidiGraphKernel {
    /// What the kernel produces.
    type Out;
    /// Run at one concrete directed view.
    fn call<G>(self, g: G) -> Self::Out
    where
        G: gt_core::graph::Bidirectional + VertexList + EdgeList + Endpoints;
}

/// A graph plus the runtime choice of view.
pub struct AnyGraph<'g, H: Lookup = NoLookup> {
    base: &'g AdjList<H>,
    kind: ViewKind,
    vmask: &'g [u8],
    emask: &'g [u8],
}

impl<'g, H: Lookup> AnyGraph<'g, H> {
    /// An unfiltered view.
    pub fn new(base: &'g AdjList<H>, kind: ViewKind) -> Self {
        AnyGraph {
            base,
            kind,
            vmask: &[],
            emask: &[],
        }
    }

    /// A filtered view. The masks are validated when the view is built.
    pub fn filtered(
        base: &'g AdjList<H>,
        kind: ViewKind,
        vmask: &'g [u8],
        emask: &'g [u8],
    ) -> Self {
        AnyGraph {
            base,
            kind,
            vmask,
            emask,
        }
    }

    /// Which view.
    #[inline]
    pub const fn kind(&self) -> ViewKind {
        self.kind
    }

    /// Run `kernel` at the concrete view.
    ///
    /// An exhaustive `match` with no catch-all: adding a seventh
    /// [`ViewKind`] is `error[E0004]: non-exhaustive patterns`, where
    /// graph-tool's linear `any_cast` scan gives a runtime
    /// `DispatchNotFound` whose message is "This is a graph_tool bug. :-("
    /// (`dispatch.hh:86-88`).
    pub fn dispatch<K: GraphKernel>(self, kernel: K) -> Result<K::Out, ViewError> {
        let AnyGraph {
            base,
            kind,
            vmask,
            emask,
        } = self;
        // Six arms, six *types*. Each `kernel.call` below is a separate
        // monomorphisation -- `&AdjList<H>`, `Und<&AdjList<H>>`,
        // `Rev<&AdjList<H>>` and the three `Filtered<_, MaskFilter>` wrappers
        // -- which is what `run_action`'s generic lambda
        // (`graph_filtering.hh:189-200`) gets from the Hana scan, without the
        // scan.
        match kind {
            ViewKind::Directed => Ok(kernel.call(base)),
            ViewKind::Undirected => Ok(kernel.call(as_undirected(base))),
            ViewKind::Reversed => Ok(kernel.call(as_reversed(base))),
            ViewKind::DirectedFiltered => Ok(kernel.call(as_filtered(base, vmask, emask)?)),
            ViewKind::UndirectedFiltered => {
                Ok(kernel.call(as_filtered(as_undirected(base), vmask, emask)?))
            }
            ViewKind::ReversedFiltered => {
                Ok(kernel.call(as_filtered(as_reversed(base), vmask, emask)?))
            }
        }
    }

    /// Run a predecessor-using kernel. Only the directed arms exist.
    ///
    /// Those are [`ViewKind::DIRECTED`] -- `always_directed`
    /// (`graph_filtering.hh:135-138`), four views -- and the two undirected
    /// kinds are refused rather than answered with the empty in-range of
    /// `graph_adaptor.hh:219-227`. The match is still exhaustive with no
    /// catch-all, so a seventh [`ViewKind`] is `error[E0004]` here too.
    pub fn dispatch_bidi<K: BidiGraphKernel>(self, kernel: K) -> Result<K::Out, ViewError> {
        let AnyGraph {
            base,
            kind,
            vmask,
            emask,
        } = self;
        match kind {
            ViewKind::Directed => Ok(kernel.call(base)),
            ViewKind::Reversed => Ok(kernel.call(as_reversed(base))),
            ViewKind::DirectedFiltered => Ok(kernel.call(as_filtered(base, vmask, emask)?)),
            ViewKind::ReversedFiltered => {
                Ok(kernel.call(as_filtered(as_reversed(base), vmask, emask)?))
            }
            offered @ (ViewKind::Undirected | ViewKind::UndirectedFiltered) => {
                Err(ViewError::NotDirected {
                    offered,
                    accepted: &ViewKind::DIRECTED,
                })
            }
        }
    }
}

/// The dyn-compatible face of a graph.
///
/// The Python boundary is runtime dispatch over graph kinds, and
/// [`GraphRef`] is deliberately not a trait object: internal iteration is
/// dyn-compatible, keeps the monomorphised `fold` fast path inside the callee,
/// and costs one indirect call per **vertex** rather than per edge.
///
/// A GAT-based incidence trait would make this impossible outright
/// (`error[E0038]: the trait is not dyn compatible because it contains
/// generic associated type OutEdges`), which is the single strongest argument
/// against that shape.
pub trait DynGraph {
    /// Honest vertex count of this view.
    fn num_vertices(&self) -> usize;
    /// Honest edge count of this view.
    fn num_edges(&self) -> usize;
    /// Visit `v`'s out-edges.
    fn for_each_out(&self, v: VertexId, f: &mut dyn FnMut(Incident));
    /// Visit every vertex.
    fn for_each_vertex(&self, f: &mut dyn FnMut(VertexId));
}

impl<G> DynGraph for G
where
    G: GraphRef + VertexList,
{
    #[inline]
    fn num_vertices(&self) -> usize {
        GraphBaseExt::nv(*self)
    }
    #[inline]
    fn num_edges(&self) -> usize {
        GraphBaseExt::ne(*self)
    }
    #[inline]
    fn for_each_out(&self, v: VertexId, f: &mut dyn FnMut(Incident)) {
        (*self).out_edges(v).for_each(f);
    }
    #[inline]
    fn for_each_vertex(&self, f: &mut dyn FnMut(VertexId)) {
        (*self).vertices().for_each(f);
    }
}

/// Disambiguates the inherent-versus-trait method names inside the blanket
/// [`DynGraph`] impl, where `self.num_vertices()` would recurse.
trait GraphBaseExt: gt_core::graph::GraphBase {
    #[inline]
    fn nv(self) -> usize {
        gt_core::graph::GraphBase::num_vertices(self)
    }
    #[inline]
    fn ne(self) -> usize {
        gt_core::graph::GraphBase::num_edges(self)
    }
}
impl<G: gt_core::graph::GraphBase> GraphBaseExt for G {}

/// Build the undirected view of a graph. Helper for the dispatch arms.
#[inline]
pub fn as_undirected<H: Lookup>(g: &AdjList<H>) -> gt_core::view::Und<&AdjList<H>> {
    g.undirect()
}

/// Build the reversed view of a graph. Helper for the dispatch arms.
#[inline]
pub fn as_reversed<H: Lookup>(g: &AdjList<H>) -> gt_core::view::Rev<&AdjList<H>> {
    g.reverse()
}

/// Build a mask-filtered view of any base view.
#[inline]
pub fn as_filtered<'m, G>(
    g: G,
    vmask: &'m [u8],
    emask: &'m [u8],
) -> Result<Filtered<G, MaskFilter<'m>>, gt_core::error::PropError>
where
    G: GraphRef + VertexList + EdgeList,
{
    Filtered::masked(g, vmask, emask)
}
